name: MacOS

on:
  push:
    tags:
      - 'v*'
    paths:
      - 'QtScrcpy/**'
      - '!QtScrcpy/res/**'
      - '.github/workflows/macos.yml'
  pull_request:
    paths:
      - 'QtScrcpy/**'
      - '!QtScrcpy/res/**'
      - '.github/workflows/macos.yml'

permissions:
  contents: write

jobs:
  build:
    name: Build
    runs-on: macos-13

    strategy:
      matrix:
        qt-ver: [5.15.2, 6.5.3]
        include:
          - qt-ver: 5.15.2
            qt-arch-install: clang_64
            build-arch: x64
          - qt-ver: 6.5.3
            qt-arch-install: arm64
            build-arch: arm64

    env:
      target-name: QtScrcpy
      qt-install-path: ${{ github.workspace }}/${{ matrix.qt-ver }}
      platform-des: mac

    steps:
      - name: Cache Qt
        id: cache-qt
        uses: actions/cache@v4
        with:
          path: ${{ env.qt-install-path }}/${{ matrix.qt-arch-install }}
          key: ${{ runner.os }}-${{ matrix.qt-ver }}-${{ matrix.qt-arch-install }}

      - name: Install Qt5
        if: startsWith(matrix.qt-ver, '5.')
        uses: jurplel/install-qt-action@v4.1.1
        with:
          version: ${{ matrix.qt-ver }}
          target: desktop
          arch: ${{ matrix.qt-arch-install }}
          cached: ${{ steps.cache-qt.outputs.cache-hit }}

      - name: Install Qt6
        if: startsWith(matrix.qt-ver, '6.')
        uses: jurplel/install-qt-action@v4.1.1
        with:
          version: ${{ matrix.qt-ver }}
          target: desktop
          arch: ${{
